# 该文件添加到了.ignore文件中，所以不会被上传到github上

server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course-system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: sirius
    password: 132239
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.project.entity
  global-config:
    db-config:
      id-type: auto
      
logging:
  level:
    com.example.project.mapper: debug
    org.springframework.jdbc.core: debug
  file:
    name: logs/spring-boot-app.log